# Generated by Django 5.2 on 2025-04-30 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование бренда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование склада')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость (единиц)')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.AddField(
            model_name='sportproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstproject.brand', verbose_name='Бренд'),
        ),
        migrations.CreateModel(
            name='EquipmentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255, verbose_name='Название характеристики')),
                ('feature_value', models.CharField(max_length=255, verbose_name='Значение характеристики')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='firstproject.sportproduct', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика оборудования',
                'verbose_name_plural': 'Характеристики оборудования',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Поступление'), ('out', 'Списание'), ('transfer', 'Перемещение')], max_length=20, verbose_name='Тип движения')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата движения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstproject.sportproduct', verbose_name='Товар')),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_movements', to='firstproject.warehouse', verbose_name='Склад назначения')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstproject.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Движение стока',
                'verbose_name_plural': 'Движения стоков',
            },
        ),
    ]
