# Generated by Django 5.2 on 2025-04-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0002_brand_warehouse_sportproduct_brand_equipmentfeature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
