# Generated by Django 5.2 on 2025-04-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0003_alter_sportproduct_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
