# Generated by Django 5.2 on 2025-05-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0004_alter_clothes_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категорииииии'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование категориииии'),
        ),
        migrations.AlterField(
            model_name='sportproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
    ]
